heat_template_version: 2014-10-16

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: firstboot_config}

  firstboot_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        list_join:
        - ''
        - - get_file: hook_scripts/wipe_disk.sh
          - get_file: hook_scripts/firstboot.sh
          - get_file: hook_scripts/package.sh

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
